#!/bin/bash

system='pbs'  # slurm, or pbs
queue='sandyq'
max_nproc_per_node=16 # max number of cpus per node
ntasks=4 # ntasks
NPROC=4  # cpu for each task
WallTime=1 # request time
FC='ifort'
MPIFC='mpif90'
